export const DEGREES = [
  "Bachelor of Computer Applications (BCA)",
  "Master of Computer Applications (MCA)",
  "Bachelor of Technology (B.Tech)",
  "Master of Technology (M.Tech)",
  "Bachelor of Science (B.Sc)",
  "Master of Science (M.Sc)",
  "Bachelor of Commerce (B.Com)",
  "Master of Commerce (M.Com)",
  "Bachelor of Arts (B.A)",
  "Master of Arts (M.A)",
  "Bachelor of Business Administration (BBA)",
  "Master of Business Administration (MBA)",
  "Diploma",
  "Doctor of Philosophy (PhD)"
];

export const UNIVERSITIES = [
  "Aligarh Muslim University (AMU)",
  "Amity University, Kolkata",
  "Amity University, Lucknow",
  "Amity University, Noida",
  "Amity University, Patna",
  "Amrita Vishwa Vidyapeetham",
  "Andhra University",
  "Anna University",
  "Apex Professional University, Pasighat",
  "Ashoka University, Sonipat",
  "Assam Don Bosco University, Guwahati",
  "Assam Down Town University, Guwahati",
  "Banasthali Vidyapith",
  "Bangalore University",
  "Bharati Vidyapeeth, Pune",
  "BHU",
  "Birla Institute of Technology (BIT), Mesra",
  "Birla Institute of Technology and Science (BITS), Pilani",
  "BITS Pilani, Hyderabad Campus",
  "BMS College of Engineering, Bengaluru",
  "Brainware University, Kolkata",
  "Calcutta University",
  "Centurion University, Paralakhemundi",
  "Chaitanya Bharathi Institute of Technology (CBIT), Hyderabad",
  "Chandigarh University",
  "Chitkara University, Himachal Campus",
  "Chitkara University, Rajpura",
  "Christ University, Bengaluru",
  "CUSAT",
  "D.Y. Patil Vidyapeeth, Navi Mumbai",
  "D.Y. Patil Vidyapeeth, Pune",
  "Delhi Technological University (DTU)",
  "Dhirubhai Ambani Institute of Information and Communication Technology (DA-IICT), Gandhinagar",
  "DIT University, Dehradun",
  "Dr. C.V. Raman University, Bilaspur",
  "Galgotias University, Greater Noida",
  "GB Pant University",
  "GITAM, Visakhapatnam",
  "GNDU, Amritsar",
  "Grant Medical College",
  "Graphic Era University, Dehradun",
  "Guru Gobind Singh Indraprastha University (GGSIPU)",
  "HBTU",
  "Heritage Institute of Technology, Kolkata",
  "Hidayatullah National Law University",
  "HPU",
  "ICFAI University, Ranchi",
  "ICFAI University, Sikkim",
  "ICFAI University, Tripura",
  "ICT Mumbai",
  "IIM Ahmedabad",
  "IISc",
  "IIT Bombay",
  "IIT Delhi",
  "IIT Dhanbad (ISM)",
  "IIT Gandhinagar",
  "IIT Guwahati",
  "IIT Hyderabad",
  "IIT Indore",
  "IIT Jodhpur",
  "IIT Kanpur",
  "IIT Kharagpur",
  "IIT Madras",
  "IIT Mandi",
  "IIT Patna",
  "IIT Roorkee",
  "IIT Ropar",
  "Institute of Engineering and Management (IEM), Kolkata",
  "International Institute of Information Technology (IIIT), Hyderabad",
  "ITM University, Gwalior",
  "ITM University, Raipur",
  "Jadavpur University",
  "Jagran Lakecity University, Bhopal",
  "Jain University, Bengaluru",
  "Jamia Hamdard",
  "Jamia Millia Islamia",
  "Jawaharlal Nehru University (JNU)",
  "Jaypee Institute of Information Technology (JIIT), Noida",
  "Jaypee University of Information Technology, Solan",
  "K.J. Somaiya, Mumbai",
  "K.K. University, Nalanda",
  "Kalinga Institute of Industrial Technology (KIIT), Bhubaneswar",
  "Kalinga University, Raipur",
  "Kerala University",
  "KGMU",
  "Koneru Lakshmaiah Education Foundation (KL University), Guntur",
  "Kurukshetra University",
  "Lakshmi Narain College of Technology (LNCT), Bhopal",
  "LNMIIT, Jaipur",
  "Lovely Professional University (LPU)",
  "Manav Rachna International Institute of Research and Studies, Faridabad",
  "Manipal Academy of Higher Education (MAHE), Manipal",
  "Manipal University, Jaipur",
  "MANIT Bhopal",
  "Martin Luther Christian University, Shillong",
  "MATS University, Raipur",
  "Medi-Caps University, Indore",
  "MIT World Peace University (MIT-WPU), Pune",
  "MMC",
  "MNIT Jaipur",
  "MSU Baroda",
  "Narsee Monjee Institute of Management Studies (NMIMS), Mumbai",
  "Netaji Subhas Medical College & Hospital, Patna",
  "Netaji Subhas University of Technology (NSUT)",
  "NIMS University, Jaipur",
  "Nirma University, Ahmedabad",
  "NIT Calicut",
  "NIT Hamirpur",
  "NIT Jamshedpur",
  "NIT Kurukshetra",
  "NIT Patna",
  "NIT Raipur",
  "NIT Rourkela",
  "O.P. Jindal Global University, Sonipat",
  "Osmania University",
  "Pandit Deendayal Energy University (PDEU), Gandhinagar",
  "Panjab University, Chandigarh",
  "Parul University, Vadodara",
  "Patna University",
  "PES University, Bengaluru",
  "R.V. College of Engineering (RVCE), Bengaluru",
  "Rajagiri College of Social Sciences, Kochi",
  "Ramaiah Institute of Technology (MSRIT), Bengaluru",
  "Royal Global University, Guwahati",
  "Sage University, Bhopal",
  "Sage University, Indore",
  "Sandip University, Madhubani",
  "SASTRA Deemed University, Thanjavur",
  "Sathyabama Institute, Chennai",
  "Saveetha Institute of Medical and Technical Sciences, Chennai",
  "SCMS School of Engineering and Technology, Kochi",
  "Sharda University, Greater Noida",
  "Shiv Nadar University, Greater Noida",
  "Shoolini University, Solan",
  "Siksha 'O' Anusandhan (SOA), Bhubaneswar",
  "Sikkim Manipal University, Gangtok",
  "Sister Nivedita University, Kolkata",
  "SPPU, Pune",
  "SRM Institute of Science and Technology, Chennai",
  "SSN College of Engineering, Chennai",
  "St. Joseph University, Dimapur",
  "Swami Rama Himalayan University",
  "Symbiosis International University, Pune",
  "TERI School of Advanced Studies",
  "Tezpur University",
  "Thapar Institute of Engineering and Technology, Patiala",
  "The NorthCap University, Gurugram",
  "University of Delhi (DU)",
  "University of Petroleum and Energy Studies (UPES), Dehradun",
  "University of Science and Technology Meghalaya (USTM)",
  "Usha Martin University, Ranchi",
  "Utkal University",
  "Vellore Institute of Technology (VIT)",
  "Vignan’s Foundation for Science, Technology & Research, Guntur",
  "Woxsen University, Hyderabad",
  "Xavier Labor Relations Institute (XLRI), Jamshedpur"
];

export const MAJORS = [
  "Computer Science", "Information Technology", "Artificial Intelligence",
  "Data Science", "Machine Learning", "Cyber Security", "Software Engineering",
  "Cloud Computing", "Electronics & Communication", "Electrical Engineering",
  "Mechanical Engineering", "Civil Engineering", "Business Administration",
  "Commerce", "Economics", "Mathematics", "Physics", "Statistics"
];

export const LOCATIONS = [
  "Bengaluru", "Mumbai", "Delhi", "Gurugram", "Noida", "Pune", "Hyderabad",
  "Chennai", "Kolkata", "Ahmedabad", "Remote", "Hybrid"
];

export const ROLES = [
  "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer",
  "Data Scientist", "Machine Learning Engineer", "Product Manager", "UI/UX Designer",
  "DevOps Engineer", "QA Engineer", "Business Analyst", "System Administrator",
  "Mobile Developer", "Cloud Engineer", "Game Developer"
];

// 🎨 Deterministic Color Palette
export const ROLE_COLORS = [
  "bg-indigo-600 text-white hover:bg-indigo-700 border-transparent shadow-sm shadow-indigo-200 dark:shadow-none",
  "bg-blue-600 text-white hover:bg-blue-700 border-transparent shadow-sm shadow-blue-200 dark:shadow-none",
  "bg-emerald-600 text-white hover:bg-emerald-700 border-transparent shadow-sm shadow-emerald-200 dark:shadow-none",
  "bg-amber-600 text-white hover:bg-amber-700 border-transparent shadow-sm shadow-amber-200 dark:shadow-none",
  "bg-rose-600 text-white hover:bg-rose-700 border-transparent shadow-sm shadow-rose-200 dark:shadow-none",
  "bg-cyan-600 text-white hover:bg-cyan-700 border-transparent shadow-sm shadow-cyan-200 dark:shadow-none",
  "bg-fuchsia-600 text-white hover:bg-fuchsia-700 border-transparent shadow-sm shadow-fuchsia-200 dark:shadow-none",
  "bg-orange-600 text-white hover:bg-orange-700 border-transparent shadow-sm shadow-orange-200 dark:shadow-none",
  "bg-teal-600 text-white hover:bg-teal-700 border-transparent shadow-sm shadow-teal-200 dark:shadow-none",
  "bg-indigo-600 text-white hover:bg-indigo-700 border-transparent shadow-sm shadow-indigo-200 dark:shadow-none",
];

export const getRoleColor = (role: string) => {
  if (!role) return ROLE_COLORS[0];
  let hash = 0;
  for (let i = 0; i < role.length; i++) {
    hash = role.charCodeAt(i) + ((hash << 5) - hash);
  }
  const index = Math.abs(hash) % ROLE_COLORS.length;
  return ROLE_COLORS[index];
};

export const getGraduationYears = () => {
  const currentYear = new Date().getFullYear();
  const startYear = currentYear - 6;
  const endYear = currentYear + 2;
  const years = [];
  for (let i = endYear; i >= startYear; i--) {
    years.push(i.toString());
  }
  return years;
};
